### ISSUE TITLE
Unable to Commit

### ISSUE THREAD

**Issue by grayloon** [ataylorme/wordpress-at-scale-auto-update#13]
Everything works great until I get to [line 60](https://github.com/ataylorme/wordpress-at-scale-auto-update/blob/master/bin/wordpress-at-scale-auto-update.sh#L60) of wordpress-at-scale-auto-update.sh. After the multidev has been put into SFTP mode and plugins have been installed, I'm unable to commit. I get an error:
There is no code to commit.

In the Pantheon Dashboard, there are no changed files shown. If I refresh the dashboard, it shows changed files are ready to commit, and I can run the terminus command to commit them.

Is there some way to make terminus recognize that files have changed?

**Comment by stevector** [comment]
This problem is a bug in Terminus: https://github.com/pantheon-systems/terminus/issues/1115

**Comment by ataylorme** [comment]
@grayloon please try `env:clear-cache` or using the `--force` flag for the commit command.
