### ISSUE TITLE
Switch to CircleCI Cron

### ISSUE THREAD

**Issue by ataylorme** [ataylorme/wordpress-at-scale-auto-update#14]
CircleCI has native cron we should be using instead of pinging the API. See [this doc](https://docs.travis-ci.com/user/cron-jobs/). cc @stevector

**Comment by stevector** [comment]
@ataylorme that link goes to Travis documentation. CircleCI still does not have native cron (to my knowledge)

**Comment by ataylorme** [comment]
d'oh - will need to port to Travis then. Although the blog post references CircleCI. Maybe I can update it as well.
