### ISSUE TITLE
Break off into a generic project

### ISSUE THREAD

**Issue by davidneedham** [ataylorme/wordpress-at-scale-auto-update#15]
This project should be broken off into a generic "wordpress-auto-update" repo. As it is, settings specific to scalewp.io are here. This works great as an example, but it makes things a more complicated for the person forking the project:
 - Users have to find and replace scalewp or wordpress-at-scale is mentioned and change it to their own project name. This process is likely to introduce errors and some instances are likely to be missed.
 - This increases the complexity of setting up the project by adding more steps involving editing more files.
 - The visual regression tests immediately pass the first time the project successfully runs even if the forker hasn't finished updating all of the configuration. This can result in situations where scalewp.io is tested, passes, and code is deployed directly to the Live environment on the user's project unintentionally. (This actually happened to me.)

The first point could be mitigated by adding a site name variable at the top of bin/wordpress-at-scale-auto-update.sh (that filename could be genericized too). Maybe I'll make another issue for this particular request.

**Comment by alexfornuto** [comment]
👍 

Here's the [first instance](https://github.com/ataylorme/wordpress-at-scale-auto-update/blob/8b01c99346e029c3cfc728d6bd3cd828b11fd6f1/bin/auto-update.sh#L108) I found of a specific line that breaks usage for generic sites.

Technically [this](https://github.com/ataylorme/wordpress-at-scale-auto-update/blob/8b01c99346e029c3cfc728d6bd3cd828b11fd6f1/bin/auto-update.sh#L4) is the first site-specific reference, but it only affects Slack notifications.

**Comment by stevector** [comment]
@davidneedham, @alexfornuto, what do you think the form of that repo should be? Bash scripts, Terminus Plugin, something else? How do you envision per-site configuration happening?

**Comment by davidneedham** [comment]
I've been thinking about it as a bash script where you change all of your site-specific settings in one place within a file. I suppose not editing the files at all and passing variables via argument would be even better.

**Comment by alexfornuto** [comment]
I've been configuring mine with the variable SITE_URL, passed from Circle. If/when I ever get it working, I'll do it again from scratch as a fork, so that it can be PR'd.

**Comment by ataylorme** [comment]
Closing this as the CircleCI 2.0 updates allow sites to be configured in the `sites-to-auto-update.json` file.
