### ISSUE TITLE
Make bin/wordpress-at-scale-auto-update.sh more reusable

### ISSUE THREAD

**Issue by davidneedham** [ataylorme/wordpress-at-scale-auto-update#16]
Similar to the existing `MULTIDEV` variable, there should be a `SITENAME` variable to make `bin/wordpress-at-scale-auto-update.sh` easier to reuse on other projects.

In the interest of genericizing the rest of the project and making it easier for others, the file should be renamed to something simpler. Perhaps `auto-update.sh`.

**Comment by davidneedham** [comment]
#17

**Comment by davidneedham** [comment]
Pull request to rename the file: #18

**Comment by ataylorme** [comment]
> In the interest of genericizing the rest of the project and making it easier for others, the file should be renamed to something simpler. Perhaps `auto-update.sh`.

I agree with this
