### ISSUE TITLE
Only run check when the job is started via API

### ISSUE THREAD

**Issue by ataylorme** [ataylorme/wordpress-at-scale-auto-update#19]
See [this nightly build article](https://circleci.com/docs/1.0/nightly-builds/). Currently when commits are made to the repo CircleCI is running the update check.

This should only happen when CircleCI is ran via the API.

**Comment by stevector** [comment]
Circle 2.0 is adding the ability to define separate jobs: https://circleci.com/docs/2.0/defining-multiple-jobs/ That to me seems like a clean way to merge what this repo does with something like https://github.com/ataylorme/Advanced-WordPress-on-Pantheon

What happens in https://github.com/ataylorme/Advanced-WordPress-on-Pantheon would be the main build job. Checking for and applying security updates would be a separate job.

**Comment by ataylorme** [comment]
@stevector that does sounds like a very clean way to separate things. Moving the Advanced WordPress repo over to Circle 2.0 is on my to-do list. This method would make Behat and other items that repo is doing easier to run conditionally as well.

**Comment by ataylorme** [comment]
@stevector in the meantime can you add an environment variable, say `CRON_BUILD=1`, to your API calls? I can update the current CirlceCI `1.x` version to check for the presence of that variable.

**Comment by stevector** [comment]
@ataylorme yes, I have updated my settings. 
![screen shot 2017-07-11 at 2 45 13 pm](https://user-images.githubusercontent.com/211029/28087335-b7e52560-6647-11e7-8f9a-fb2865472bdb.png)
