### ISSUE TITLE
Terminus installation method

### ISSUE THREAD

**Issue by stevector** [ataylorme/wordpress-at-scale-auto-update#2]
I recommending using Composer global to install Terminus. The current method will not install newer versions as they come out:

```
    - sudo curl https://github.com/pantheon-systems/terminus/releases/download/0.11.3/terminus.phar -L -o /usr/local/bin/terminus
```

**Comment by ataylorme** [comment]
Closing this as the CircleCI 2.0 updates are using a custom Docker image with Terminus installed
