### ISSUE TITLE
Visual Regression Failures (HTTP vs HTTPS)

### ISSUE THREAD

**Issue by cdoggyd** [ataylorme/wordpress-at-scale-auto-update#36]
My live site is using HTTPS everywhere. When I ran the test through CircleCI, the visual regression tests failed with all the differences being custom fonts. In my xxx.backstop.json file, both the url and referenceUrl are using HTTPS. When I view source on the multidev environment, it's trying to load the Google fonts over HTTP. The browser is blocking those calls and causing the visual regression failures.

I viewed the Terminus docs, and I don't any way to "convert URLs" like you can when using the dashboard in the Dev, Test, and Live environments.

Should I just use HTTP for the multidev environment visual regression tests? Or, is there some other workaround?

**Comment by ataylorme** [comment]
> I viewed the Terminus docs, and I don't any way to "convert URLs" like you can when using the dashboard in the Dev, Test, and Live environments.

You can do this with Terminus and wp-cli using [search and replace](https://developer.wordpress.org/cli/commands/search-replace/)

I would work on trying to get the mixed content fixed and be able to run HTTPS on the multidev manually first. I think the standard Google Font snippet uses `//some-url` which loads whatever the request came in as.

It might help to redirect to HTTPS. This is the snippet I use in `wp-config.php` to do that.

```php
/**
 * Redirect to HTTPS
 */
if (isset($_SERVER['PANTHEON_ENVIRONMENT'])
  && php_sapi_name() != 'cli' ) {
  if ( !isset($_SERVER['HTTP_X_SSL'])
      || $_SERVER['HTTP_X_SSL'] != 'ON') {
    // Name transaction "redirect" in New Relic for improved reporting (optional)
    if (extension_loaded('newrelic')) {
      newrelic_name_transaction("redirect");
    }

    header('HTTP/1.0 301 Moved Permanently');
    header('Location: https://'. $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']);

    exit();
  }
}
```
