### ISSUE TITLE
$UPDTE_TAG instead of $UPDATE_TAG typo in setup-globals.sh

### ISSUE THREAD

**Issue by jadonn** [ataylorme/wordpress-at-scale-auto-update#38]
It looks like the set-up-globals.sh script has a typo at line 24 where it says $UPDTE_TAG instead of $UPDATE_TAG.

https://github.com/ataylorme/wordpress-at-scale-auto-update/blob/5bb8b8344ef6b9b449ca75d1aaaf1e0ef8699b7e/.circleci/set-up-globals.sh#L24-L27

**Comment by ataylorme** [comment]
Thanks for letting me know. `UPDATE_TAG` is declared but never used anywhere. I plan to remove it.
