### ISSUE TITLE
Backstop.js report not created

### ISSUE THREAD

**Issue by conantp** [ataylorme/wordpress-at-scale-auto-update#51]
Hi Pantheon! 

I'm having an issue with the backstop.js part of this routine - it seems that about 80% of the time, the visual regression test job fails with this message: 

Diff report file /tmp/artifacts/backstop_data/html_report/index.html not found for {site_name}

If I rebuild a few times on that step, it sometimes completes. Do you have any idea why this might be happening? 

Here's the output I get on CircleCI:

Rsyncing backstop_data files to /tmp/artifacts for anonymous-public-records-requests...
sending incremental file list
backstop_data/
backstop_data/bitmaps_reference/
backstop_data/bitmaps_reference/285175078___0_document_0_phone.png
backstop_data/bitmaps_reference/285175078___0_document_1_desktop.png
backstop_data/bitmaps_reference/285175078__completed-requests__0_document_0_phone.png
backstop_data/bitmaps_reference/285175078__completed-requests_government_entityother_0_document_0_phone.png
backstop_data/bitmaps_reference/285175078__completed-requests_government_entityother_0_document_1_desktop.png
backstop_data/bitmaps_reference/285175078__records_request_haywood-county-schools-eeoc-complaints__0_document_0_phone.png
backstop_data/bitmaps_reference/285175078__records_request_haywood-county-schools-eeoc-complaints__0_document_1_desktop.png
backstop_data/bitmaps_test/
backstop_data/bitmaps_test/20190304-063349/
backstop_data/bitmaps_test/20190304-063349/285175078___0_document_0_phone.png
backstop_data/bitmaps_test/20190304-063349/285175078___0_document_1_desktop.png
backstop_data/bitmaps_test/20190304-063349/285175078__completed-requests__0_document_0_phone.png
backstop_data/bitmaps_test/20190304-063349/285175078__completed-requests_government_entityother_0_document_0_phone.png
backstop_data/bitmaps_test/20190304-063349/285175078__completed-requests_government_entityother_0_document_1_desktop.png
backstop_data/bitmaps_test/20190304-063349/285175078__records_request_haywood-county-schools-eeoc-complaints__0_document_0_phone.png
backstop_data/bitmaps_test/20190304-063349/285175078__records_request_haywood-county-schools-eeoc-complaints__0_document_1_desktop.png
backstop_data/casper_scripts/
backstop_data/casper_scripts/onBefore.js
backstop_data/casper_scripts/onReady.js

sent 44,913,671 bytes  received 348 bytes  29,942,679.33 bytes/sec
total size is 48,158,994  speedup is 1.07

Diff report file /tmp/artifacts/backstop_data/html_report/index.html not found for anonymous-public-records-requests!
Exited with code 1

**Comment by ataylorme** [comment]
Hi @conantp,

> `Diff report file /tmp/artifacts/backstop_data/html_report/index.html not found`

The script checks for the HTML report generated by BackstopJS and fails if it can't find it.

I'm not sure why the report file would fail to be created that often. You can comment out/remove [lines 66-71](https://github.com/pantheon-systems/example-terminus-auto-update-script/blob/master/.circleci/visual-regression-test.sh#L66:L71) to disable the check for the HTML report file but then you would not be able to view the report.

**Comment by ataylorme** [comment]
I'm closing this issue so we can archive this repository. It is a reference implementation, not a product to be used. [See this comment on the README](https://github.com/pantheon-systems/example-terminus-auto-update-script#repository-archived-2019-06-13)

[This thread on the Pantheon community forum](https://discuss.pantheon.io/t/visual-regression-error-with-ci-workflow/357/) may be useful

**Comment by conantp** [comment]
@ataylorme - not a problem, and I look forward to testing out StagingPilot. I do have this script running on one of our production sites - and it works, with the backstop tests running - I just can't see the report when it fails.
